name: CI Angular app through Github Actions
on: push
jobs:
  build:
    name: NG Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 16.x
        uses: actions/setup-node@v1
        with:
          node-version: '16.15.0'
      - name: Setup
        run: npm ci
      - name: Test
        run: npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
